sudo: false
language: python
python:
  - "3.7"
  - "3.8"
env:
  # - PANDAS=dev
  - PANDAS=rel
  - PANDAS=0.24
jobs:
  include:
    - {python: "3.6", env: PANDAS=0.22}
    # Testing `force_tuple_columns` seem to require pandas 0.22--0.20.
    #
    # See: [[./src/dictsdiff/core.py::def force_tuple_columns]]
    # https://github.com/pandas-dev/pandas/issues/16769
before_install:
  - pip install --quiet tox-travis coveralls
script:
  - tox --develop -- --cov dictsdiff
notifications:
  email: false

# Only build branches via PR to avoid running CI twice.
# https://docs.travis-ci.com/user/conditional-builds-stages-jobs
# https://docs.travis-ci.com/user/conditions-v1
if: branch = master OR tag IS present OR type != push
