sudo: false
language: python
python:
  - "3.7"
  - "3.8"
env:
  # - PANDAS=dev
  - PANDAS=rel
  - PANDAS=0.24
jobs:
  include:
    - {python: "3.6", env: PANDAS=0.22}
    # Testing `force_tuple_columns` seem to require pandas 0.22--0.20.
    #
    # See: [[./src/dictsdiff/core.py::def force_tuple_columns]]
    # https://github.com/pandas-dev/pandas/issues/16769

    # Python 2.7 is supported only up to pandas 0.24:
    # http://pandas.pydata.org/pandas-docs/version/0.24/install.html#install-dropping-27
    - {python: "2.7", env: PANDAS=0.24}
    # - {python: "2.7", env: PANDAS=0.23}
    - {python: "2.7", env: PANDAS=0.22}
    # - {python: "2.7", env: PANDAS=0.21}
    # - {python: "2.7", env: PANDAS=0.20}
    - {python: "2.7", env: PANDAS=0.19}
before_install:
  - pip install --quiet tox-travis coveralls
script:
  - tox --develop -- --cov dictsdiff
  # Use --develop so that files are visible in coveralls.io
notifications:
  email: false

# Only build branches via PR to avoid running CI twice.
# https://docs.travis-ci.com/user/conditional-builds-stages-jobs
# https://docs.travis-ci.com/user/conditions-v1
if: branch = master OR tag IS present OR type != push
