sudo: false
language: python
python:
  - "2.7"
  - "3.5"
  - "3.6"
before_install:
  - pip install --quiet tox-travis coveralls
script:
  - tox --develop -- --cov dictsdiff
  # Use --develop so that files are visible in coveralls.io
after_success:
  - coveralls
