sudo: false
language: python
python:
  - "2.7"
  - "3.5"
  - "3.6"
env:
  # - PANDAS=dev
  - PANDAS=rel

  # - PANDAS=0.24
  # - PANDAS=0.23
  - PANDAS=0.22
  # Testing `force_tuple_columns` seem to require pandas 0.22--0.20.
  #
  # See: [[./src/dictsdiff/core.py::def force_tuple_columns]]
  # https://github.com/pandas-dev/pandas/issues/16769

  # - PANDAS=0.21
  # - PANDAS=0.20
  - PANDAS=0.19
before_install:
  - pip install --quiet tox-travis coveralls
script:
  - tox --develop -- --cov dictsdiff
  # Use --develop so that files are visible in coveralls.io
after_success:
  - coveralls
notifications:
  email: false
